name: final_exam
env:
  APP_NAME: "My_first_app"
  RELISE_NAME: "My_fist_app_version-${{ github.sha }}"
  FIRS_NAME: "Subhi"

on: 
  push:
    branches:
      - main
jobs:

  my_job1:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "Hello World"
    
    - name: check version
      run: lsb_release -a
      
    - name: show sha
      run: echo "Relise name ${{ env.RELISE_NAME }}"
  
  my_job2:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone
      uses: actions/checkout@v1
      
    - name: print files content
      run: sh ./test.sh
      shell: bash
      
  my_jib3:
    runs-on: ubuntu-latest
    
    steps:
    - name: print name
      run: echo "First name is ${{ env.FIRS_NAME }}"
      
     - name: print last name:
     run: echo ${{ variables.LAST_NAME }}
     
    
    - name: print phone number
      run: echo ${{ secrets.PHONE }}
