name: final_exam
env:
  APP_NAME: "My_first_app"

on: 
  push:
    branches:
      - main
jobs:

  my_job1:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: print hello world
      run: echo "Hello World"
    
    - name: check version
      run: aws -a
